fix: tls hostNameOverride
authelia/chartrepo pull request #219
Opened 2023-12-19 14:27 UTC by aleksasiriski

2023-12-20 04:38 UTC, james-d-elliott commented
What does this fix?

2023-12-20 12:32 UTC, aleksasiriski commented
I've added that to desc of the PR

2024-04-19 01:55 UTC, james-d-elliott requested changes

2024-04-19 01:55 UTC, james-d-elliott commented on charts/authelia/values.yaml
> +    hostNameOverride: ""
```suggestion
    hostNameOverride: ''
```

2024-04-19 01:58 UTC, james-d-elliott commented
Taken over locally in #230, thanks!

2024-04-19 01:58 UTC, closed without merging