Indentation fixes
authelia/chartrepo pull request #226
Opened 2024-04-08 18:46 UTC by hhomar

Hi

Just a couple of small indentation fixes found while testing 4.38.0.

2024-04-09 22:42 UTC, james-d-elliott commented
Please include examples of what this is intending on fixing as it's not clear from the changes and tests I've done.

2024-04-10 04:13 UTC, hhomar commented
# wrapYAML indentation

With the following access_control set in values.yml:

```yaml
  access_control:
    secret:
      enabled: true
      key: 'configuration.acl.yaml'
      existingSecret: ''
    default_policy: 'deny'
    networks: []
    rules:
      - domain: '*.example.com'
        policy: 'one_factor'
```

This was generating a secret with an invalid access control yaml file (indentation of access_control:):

```yaml
---
        access_control:
  default_policy: 'deny'
  rules:
    - policy: one_factor
      domain:
        - '*.example.com'
    ...
```

# oidc jwks  key indentation

With the following identity_providers oidc jwks key (other values left out for brevity):

```yaml
identity_providers:
  oidc:
    enabled: true
    jwks:
      - key:
          path: "/secrets/authelia-jwks/private.pem"
```

This would generate a secret template with an invalid indentation (mindent 8 instead of mindent 12):

```yaml
jwks:
  key: {{ secret "/secrets/authelia-jwks/private.pem" | mindent 8 "|" | msquote }}
```

Causing the following error:

Configuration: failed to load configuration from file
path(/configuration.yaml) source: yaml: line 158: could not find
expected ':'

2024-04-10 05:40 UTC, james-d-elliott commented
Ah yep, that makes sense. I'll double check it.

2024-04-10 08:29 UTC, james-d-elliott requested changes
Just this one minor change which should fix it but keep the indent consistent.

2024-04-10 08:29 UTC, james-d-elliott commented on charts/authelia/templates/configMap.yaml
> +        {{- tpl ($.Files.Get "files/configuration.oidc.jwk.yaml") (merge (dict "Key" $key "Indent" 8) $) | trim | nindent 10 }}
```suggestion
        {{- tpl ($.Files.Get "files/configuration.oidc.jwk.yaml") (merge (dict "Key" $key "Indent" 6) $) | trim | nindent 10 }}
```

2024-04-10 08:29 UTC, merged