fix(authz): allow creation of legacy server endpoint
authelia/chartrepo pull request #257
Opened 2024-08-15 09:16 UTC by gietschess

Allow the creation of legacy server enpoints as described in the [Server Authz Endpoints](https://www.authelia.com/configuration/miscellaneous/server-endpoints-authz) and [Proxy Authorization](https://www.authelia.com/reference/guides/proxy-authorization) documentation to use the legacy `/api/verify` endpoint.

Additionally fixed a validation failure message mentioning the wrong helm value.

2024-08-15 09:29 UTC, james-d-elliott commented
We do not support deprecated options within the helm chart generally. What's the use case?

2024-08-15 10:19 UTC, gietschess commented
Hi there,
i hoped as long as the binary allows the fallback to the legacy endpoint the chart would also support it.
Usecase: Allow the deprecated `api/verify` endpoint besides the new '/api/authz/auth-request' while updating the annotations on all ingress objects using authelia.

2024-08-15 20:28 UTC, james-d-elliott commented
I'd be willing to add undocumented support in the 0.9 releases and remove it in 0.10 when 4.38 comes out provided the commit was clean so I can just git revert it.

2024-08-16 06:55 UTC, gietschess commented
yes, would be totally fine with that.

2024-08-16 08:12 UTC, james-d-elliott requested changes
If you adjust this PR removing the changes to the values files, and removing the additional fix (maybe cherry-pick it into another PR) then I can commit it. This will give a clean exit strategy for the changes and give a reasonable upgrade path which I think is valuable.

2024-08-16 08:42 UTC, james-d-elliott approved these changes

2024-08-16 08:43 UTC, merged