feat: handle correctly when replicas is set to 0
authelia/chartrepo pull request #259
Opened 2024-08-16 12:25 UTC by Tchoupinax

Hello !

I need to set replicas to 0 for my Authelia deployment but there is an issue with the interpretation of `0` with default. it's a [known issue](https://github.com/helm/helm/issues/3164) with helm so I added this simple workaround.

Thanks for your work!

2024-08-17 00:27 UTC, james-d-elliott commented
Is there a particular use case for 0 replicas?

2024-08-17 05:56 UTC, Tchoupinax commented
I have deployed on application that is very occasionally used in my cluster and the app is used with Authelia. I configured sablier (https://github.com/acouvreur/sablier) on the app and it works well, I wanted to add Authelia with it but I have to configure replicas to 0 because sablier needs to manage it

2024-11-27 10:24 UTC, james-d-elliott requested changes

2024-11-27 10:24 UTC, james-d-elliott commented on charts/authelia/templates/_helpers.tpl
>          {{- default 1 .Values.pod.replicas -}}
```suggestion
        {{- .Values.pod.replicas | default 1 -}}
```

2024-11-27 10:26 UTC, merged